### ISSUE TITLE
Downloading videos of selected quality

### ISSUE THREAD

**Issue by ura23** [Avnsx/fansly-downloader#135] opened 2023-08-11 18:42 UTC
Hi, I like your program, but can you add some setting to manually set quality of the downloaded videos, because sometimes 4k is to much, if you have to download lot of videos.

**Comment by Avnsx** [comment] 2023-08-11 19:07
Duplicate of https://github.com/Avnsx/fansly-downloader/discussions/93

Also this is not a topic for issues.

**Closed by Avnsx** 2023-08-11 19:07 UTC
